[SYNC] GitLab → GitHub (#5)
* Initial commit

* Filled out README

* Renaming README file, so there's no conflict with a file in GitHub after we set up the mirror.

* Added repo path

* Adding gitlab pipeline that should create a mirror setup

* Fixing image in pipeline settings

* Another fix

* fixing unrelated histories issue

* Fix in the commit logic

* Changes to push to branch in github repo instead of main directly

* Another try

* Adding step to pull from github

* Small fix

* Solving another problem

* Adding token for gitlab to fix problem with pushing to repo from the CI pipeline

* Latest and greatest met meer merge conflict protection

* Prefer GitLab version of .gitlab-ci.yml in merges

* Adding print statement for clarity

* Lets see if it is happy now

* Update .gitlab-ci.yml file

* Nog wat meer documentatie toegevoegd.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -44,12 +44,13 @@ sync_with_github:
     - git checkout -B main origin/main
 
     # Merge GitHub main into GitLab main (allow unrelated histories first time)
-    - git merge github/main --allow-unrelated-histories --no-edit || true
+    - echo "Using .gitattributes merge rules"
+    - git merge github/main --allow-unrelated-histories --no-edit
 
     # Commit only if changes exist
     - |
       if [ -n "$(git status --porcelain)" ]; then
-        git commit -am "[SYNC] GitLab ↔ GitHub sync"
+        git commit -am "[SYNC] GitLab -> GitHub sync"
       else
         echo "No changes from GitHub to sync."
       fi
@@ -99,18 +100,24 @@ pull_github_into_gitlab:
     - git fetch github main
 
     # Checkout local main
-    - git checkout main
+    - git checkout -B main origin/main
 
     # Merge GitHub main into GitLab main
-    - git merge github/main --no-edit || true
+    - git merge github/main --allow-unrelated-histories --no-edit
+    - |
+      if git ls-files -u | grep .;
+        then echo "Merge conflicts detected. Aborting."
+        exit 1
+      fi
 
     # Commit only if there are real changes
     - |
       if [ -n "$(git status --porcelain)" ]; then
-        git commit -am "[SYNC] GitHub → GitLab sync"
+        git commit -am "[SYNC] GitHub -> GitLab sync"
       else
         echo "No changes from GitHub to sync."
       fi
 
     # Push merged changes back to GitLab main
+    - git remote set-url origin https://$GITLAB_MIRROR_USER:$GITLAB_MIRROR_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
     - git push origin main
